CREATE TABLE `wifi_info`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`event_id` BIGINT,
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	`wifi_name` VARCHAR(50),
	`wifi_password` VARCHAR(50),
	PRIMARY KEY(`id`)
);
ALTER TABLE `wifi_info`
	ADD CONSTRAINT `5d20f23f4cb33383b1a33173259d45` UNIQUE KEY(`id`);
