CREATE TABLE `data_sync_info`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	`sync_id` VARCHAR(10) NOT NULL,
	PRIMARY KEY(`sync_id`)
);
ALTER TABLE `data_sync_info`
	ADD CONSTRAINT `7a440703b8977547805f95a4f6114c` UNIQUE KEY(`sync_id`);
