CREATE TABLE `quantum_quest`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`deeplink_url` VARCHAR(512),
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`is_disabled` BOOLEAN,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`id`)
);
ALTER TABLE `quantum_quest`
	ADD CONSTRAINT `c54628c233934fece6eda9c9522bf7` UNIQUE KEY(`id`);
