CREATE TABLE `team`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`name` VARCHAR(512),
	`profile_url` VARCHAR(512),
	`SoftDeleteFlag` BOOLEAN,
	`title` VARCHAR(512),
	PRIMARY KEY(`id`)
);
ALTER TABLE `team`
	ADD CONSTRAINT `856eaca82dd999fecc8dfeb925e0f2` UNIQUE KEY(`id`);
